### ISSUE TITLE
Cannot install from "pip install driftpy"

### ISSUE THREAD

**Issue by Merlin-721** [drift-labs/driftpy#1]
As above this returns the error:

`
ERROR: Could not find a version that satisfies the requirement driftpy (from versions: none)

ERROR: No matching distribution found for driftpy
`

**Comment by kevinheavey** [comment]
Congrats on being early! This hasn't actually been published yet

**Comment by kevinheavey** [comment]
You can install it now! Mind you it's just the core and more features are being added to bring it to parity with the TypeScript client
